package com.ex.novel.domain;

public class Chapter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.novelid
     *
     * @mbggenerated
     */
    private Integer novelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.chapterName
     *
     * @mbggenerated
     */
    private String chaptername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.id
     *
     * @return the value of chapter.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.id
     *
     * @param id the value for chapter.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.novelid
     *
     * @return the value of chapter.novelid
     *
     * @mbggenerated
     */
    public Integer getNovelid() {
        return novelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.novelid
     *
     * @param novelid the value for chapter.novelid
     *
     * @mbggenerated
     */
    public void setNovelid(Integer novelid) {
        this.novelid = novelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.chapterName
     *
     * @return the value of chapter.chapterName
     *
     * @mbggenerated
     */
    public String getChaptername() {
        return chaptername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.chapterName
     *
     * @param chaptername the value for chapter.chapterName
     *
     * @mbggenerated
     */
    public void setChaptername(String chaptername) {
        this.chaptername = chaptername == null ? null : chaptername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.url
     *
     * @return the value of chapter.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.url
     *
     * @param url the value for chapter.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.content
     *
     * @return the value of chapter.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.content
     *
     * @param content the value for chapter.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}