package com.ex.novel.domain;

public class Novel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.novelName
     *
     * @mbggenerated
     */
    private String novelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.id
     *
     * @return the value of novel.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.id
     *
     * @param id the value for novel.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.novelName
     *
     * @return the value of novel.novelName
     *
     * @mbggenerated
     */
    public String getNovelname() {
        return novelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.novelName
     *
     * @param novelname the value for novel.novelName
     *
     * @mbggenerated
     */
    public void setNovelname(String novelname) {
        this.novelname = novelname == null ? null : novelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.url
     *
     * @return the value of novel.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.url
     *
     * @param url the value for novel.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}